### PR TITLE
Added a horizontal scrollbar to the contributors section

### LINKED ISSUE #111: [Site] Fix the Contributors section
**Description**

The logos listed in the [Contributors section](https://smp-spec.io/#contributors) currently occupy two lines.

**Expected Behavior**

They should be adjusted onto the same line, either by adjusting the logo sizes or more preferably by adding a horizontal scroll to the section.

**Screenshots**

Screenshot_2020-09-01 Service Mesh Performance Specification

**Environment:**
 - OS: Windows 10
 - Browser: Firefox
 - Device: Laptop
---
[Optional] **To Reproduce**
1. Go to https://smp-spec.io/
2. Click on `Contributors` in the header
3. See error

### PR DESCRIPTION
**Pull request by geraldmaboshe**
**Description**
Adjusted contributor logos display by adding a horizontal scrollbar to the contributors section

This PR fixes #111 

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.
 
@chandrashritii  @leecalcote

### CODE REVIEW

**Review by leecalcote — CHANGES_REQUESTED** [review]
@geraldmaboshe thanks for jumping in here. 👍 It's looking good so far. A couple feedback items to consider:

- remove visibility of the horizontal scrollbar
- create a carousel:
  - it could be auto-scrolling, but perhaps, for now not.
  - center the list of logos on load
  - show arrows to indicate that scrolling is possible in either direction

Ultimately, the carousel effect can be implemented different ways. Ideally, the method chosen is without javascript, if possible.

**Comment by Neilblaze** [comment]
@geraldmaboshe I'll go with the suggestion that @leecalcote mentioned. 

I shall suggest some changes over here.
- Remove the horizontal scrollbar. Replace that with a **carousel**. It'll be better if you can implement [this](https://getbootstrap.com/docs/4.3/components/carousel/#with-indicators).
- If you're going with the above, please do remove those arrows on the either side & keep *autoplay* on!
- Applying carousel imo will be a very good idea, since we don't have to think about creating new rooms for future icons.
- As he mentioned, try to avoid Javascript as much as possible!
- It'll be better if you can make the size of each of those svg's uniform, as if you see closely over [here](https://github.com/layer5io/service-mesh-performance/pull/123#pullrequestreview-484524849), some of the svg's are not properly scaled!

That's all from my side. 
@leecalcote @Nikhil-Ladha

**Comment by chandrashritii** [comment]
@Neilblaze and @leecalcote have covered all the major points. I'll just add one thing here, which will hopefully help you:
Currently, the Google and CNCF logos are the ones that need to be majorly scaled. If you are not successful in scaling them by yourself, here are a few points:
The Google logo has some extra padding on the top and bottom. Try removing the extra padding, if that doesn't work, you may look for an alternative version of the logo as well.
The CNCF logo has been taken up from the official repo, all you need to do is resize it.
The other logos simply need to be scaled to achieve a uniform alignment.

**Comment by geraldmaboshe** [comment]
@Neilblaze , on implementing bootstrap carousel, is it supposed to be one logo per slide or 4 logos on one slide and one on the second slide alone?

Or do we want to achieve something like [this](https://azmind.com/demo/bootstrap-carousel-multiple-items/)

**Comment by JubayerJoy** [comment]
> @Neilblaze , on implementing bootstrap carousel, is it supposed to be one logo per slide or 4 logos on one slide and the fifth one on the second slide alone?
> 
> Or do we want to achieve something like [this](https://azmind.com/demo/bootstrap-carousel-multiple-items/)

My suggestion would be to make it a `circular carousel`, four logos will be shown, repeatedly. It might be tricky but would be very interesting and should look good on the site. I am really interested to have the input of @Neilblaze on this.

**Review by JubayerJoy — COMMENTED** [review]
That's very good work! 🚀
Just a bit touch up with great suggestions from @leecalcote, @chandrashritii and @Neilblaze will make this lots of better.
Nicely done!

**Comment by geraldmaboshe** [comment]
> @Neilblaze , on implementing bootstrap carousel, is it supposed to be one logo per slide or 4 logos on one slide and the fifth one on the second slide alone?
> 
> Or do we want to achieve something like [this](https://azmind.com/demo/bootstrap-carousel-multiple-items/)

Hey @Neilblaze , waiting to get your input on this.

**Comment by Neilblaze** [comment]
@geraldmaboshe yep! you're right on point. I suggest you to go with your point since for transparent svg's circular/3d carousel won't look that good! Make sure you keep the autoplay on!

**Comment by Nikhil-Ladha** [comment]
All the contributors are not showing up. Only, `Layer5` and `Texas` is coming up. That too the inage of Texas is overlapping with that of Google.
Screenshot_20200916-105133__01

**Comment by geraldmaboshe** [comment]
> All the contributors are not showing up. Only, `Layer5` and `Texas` is coming up. That too the inage of Texas is overlapping with that of Google.
> Screenshot_20200916-105133__01

Yeah, I have just noticed this is happening when viewing on smaller devices, working on it

**Comment by Nikhil-Ladha** [comment]
Can this be fixed with the changes you were talking about @Neilblaze , good to have it resolved soon?

**Comment by leecalcote** [comment]
For now, the Google logo can be removed - https://github.com/layer5io/service-mesh-performance/issues/129

**Comment by geraldmaboshe** [comment]
> For now, the Google logo can be removed - #129

Cool

**Comment by Neilblaze** [comment]
@Nikhil-Ladha yeah, I can fix this right now. But, @leecalcote just suggested to remove the Google logo for now, so if my views are right, we don't need any carousel for now. The issue can just be fixed if we reduce the number of contributors from 5 to 4, since the extra (5th) logo won't be eating extra row space.

Please correct me if I'm wrong.

**Comment by Nikhil-Ladha** [comment]
But I guess we will still be needing it for the mobile view?🤔

**Review by leecalcote — APPROVED** [review]
Thank you, @geraldmaboshe. We'll need to get a few changes going forward here, but let's get your code in place as the base for updates.

**Pull request merged**
