### PR TITLE
Updated SMP page

### PR DESCRIPTION
**Pull request by Neilblaze**
**Description**

This PR updates the following things :-

- Enlarged SMP brand logo on navbar
- Added shrink on scroll to SMP brand logo
- Reduced "SMP IN-ACTION" button drop-shadow.
- Added responsive centering of "Standardizing Service Mesh Value Measurement" and "SMP IN-ACTION" button across all devices.

**Demo**

• Before :
be4

• After :
aftr

Refer to [this](https://docs.google.com/document/d/1EnFMGyPbsQ3h-YuYE0Jutew79NrPzPNTVxLu8rvqRzE/edit)!

**Notes for Reviewers**
Will soon be updating the **contributors section**! :smile: 

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by akashgp09 — COMMENTED** [review]
Great work! LGTM  👍

**Review by Nikhil-Ladha — CHANGES_REQUESTED** [review]
Once the discussed updates are done, we are good to go. :)

**Comment by Neilblaze** [comment]
@Nikhil-Ladha :rocket:

**Review by Nikhil-Ladha — APPROVED** [review]
Good improvement here @Neilblaze 👌🏼

**Pull request merged**
