### PR TITLE
wrap card to blog post

### LINKED ISSUE #138: [Site] Create a difference in color on either side of the blog posts
**Current Behavior**
A lack of formatting on the individual blog pages has them not looking as much like articles as they could be.

**Desired Behavior**
Add color to the left and right margins or some other styling to the blog post page layout to offset the text from the page.

**Screenshot**
Screen Shot 2020-09-29 at 8 04 40 AM

### PR DESCRIPTION
**Pull request by navendu-pottekkat**
Signed-off-by: Navendu Pottekkat <navendupottekkat@gmail.com>

**Description**

Wraps a card element around the blog posts for a better look.

Screenshot from 2020-11-07 19-27-21

This PR fixes #138 

- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by Nikhil-Ladha — APPROVED** [review]

**Comment by Nikhil-Ladha** [comment]
Looks good!

**Comment by Neilblaze** [comment]
Thank you @navendu-pottekkat! The blog cards do look better!

While I'm inspecting the deploy preview from desktop, I'm getting such responsive issues.
smp

But while I'm visiting the link from my mobile, the figure of `message PerformanceTestResult` isn't displayed, so that's how the above-mentioned issue is getting by bypassed. 

Adding to the above, the footer section looks different with respect to the home page. Fix that by including the `responsive.css` stylesheet in the `page.html`.

Rest LGTM :+1:

**Review by Neilblaze — CHANGES_REQUESTED** [review]
^^

**Comment by navendu-pottekkat** [comment]
@Neilblaze The current site also seem to have this issue. It maybe be an easy fix. I will look into it.

I did not check the rest of the code, I assumed it was working correctly. I will fix all these issues and commit to this PR itself.

**Comment by Neilblaze** [comment]
> @Neilblaze It maybe be an easy fix. I will look into it. But I do not know what must have broken it. Any idea?
> 
There is no defined styling for the `snippet block` for the blog posts. Generally, for the desktop view, it remains fine, but for mobile view we need to define the respective media queries regarding those since those are being populated via a .md file.

For now, just fix the footer section & we'll merge it. You are always welcomed to create another issue regarding the mentioned [issue](https://github.com/layer5io/service-mesh-performance/pull/152#issuecomment-723459811) & work on that!

**Comment by navendu-pottekkat** [comment]
Yes, I will do that.

**Comment by navendu-pottekkat** [comment]
> Fix that by including the `responsive.css` stylesheet in the `page.html`.

Will adding that to `head.html` work? As we are including that in `page.html` and no other head tags are included in that file. @Neilblaze

**Comment by navendu-pottekkat** [comment]
@Neilblaze I have added the `responsive.css` stylesheet. Please check and merge

**Review by Neilblaze — APPROVED** [review]
@navendu-pottekkat apologies for not responding, my exams are going on. The footer section looks still the same. Well, no issues. I'll have a look into it anytime soon!

LGTM :+1:

**Pull request merged**
