### PR TITLE
package-name: SMPS to SMP

### LINKED ISSUE #114: Change from SMPS to SMP as the package name
**Description**
Stale references to SMPS are still present in the proto files and package names - https://github.com/layer5io/service-mesh-performance/blob/master/smps.proto#L3

**Expected Behavior**
These should be SMP.

### PR DESCRIPTION
**Pull request by kalradev**
Signed-off-by: Dev Kalra <kalradev@outlook.com>

**Description**

This PR fixes #114 

**Notes for Reviewers**
Package name changed from SMPS to SMP in all proto files

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — CHANGES_REQUESTED** [review]
These updates look good. Here are two others to account for:

- https://github.com/layer5io/service-mesh-performance/blob/c8e23617ce04ae7f69c0738adb90e25b130b69e2/smps.proto#L30
- https://github.com/layer5io/service-mesh-performance/blob/c8e23617ce04ae7f69c0738adb90e25b130b69e2/Makefile#L2

**Review by kushthedude — CHANGES_REQUESTED** [review]
Please get rid of SMPS from everywhere, reinitialise the go mod or change the module name to service-mesh-performance

**Comment by kalradev** [comment]
I am making these changes. Should I merge metadata.proto and trafic_metadata.json, it makes more sense to me.

**Comment by kushthedude** [comment]
Yes, see https://github.com/layer5io/service-mesh-performance/issues/44, metadata needs to be merged into the traffic spec.

**Comment by kalradev** [comment]
I am recompiling the proto filles. The output folder as per the proto files is spec. 
But right now the compiled files is in perf folder. 
Also, everywhere in meshery the package is refered to be in the spec folder.
So, what should I name the output folder?

**Comment by kushthedude** [comment]
Let's go on one issue per PR as of now, the merging and restructuring can
be done later when the package is renamed.

**Comment by kushthedude** [comment]
Even the prototool needs to be configured and the spec needs to be
restructured properly according to standard protobuf rules which prototool
will help us enforce.

**Comment by kalradev** [comment]
I am not merging files.Will do that in future PRs. But we have to rebuild the files as they have been changed.

**Comment by kushthedude** [comment]
Btw you can go merge the files and rebuild the protos in the perf folder as
they are now, no issues in there.

**Comment by kushthedude** [comment]
Regarding your concern for referencing projects, we won't make release or
update the smps package referenced. So I dont see any issues in any
revamping rn.

**Comment by kalradev** [comment]
Lee assigned me https://github.com/layer5io/meshery/issues/1542
So I am going to update meshery after this PR. I can change the path to perf in that or keep it to spec.

**Comment by leecalcote** [comment]
I vote for `spec`. SMP is a specification. We just don't want that word in its name. "Specification" as a word will be assigned to SMP naturally.

**Comment by kalradev** [comment]
Okay, So I have changed the directory to spec. We can merged this now.

**Comment by kalradev** [comment]
Hey @leecalcote @kushthedude 
I have changed the directory to spec. I think now we can merge this.

**Review by leecalcote — APPROVED** [review]
LGTM

**Pull request merged**
