### PR TITLE
Create site_update.md

### LINKED ISSUE #163: Create GitHub Issue Template for Site Updates
**Current Behavior**
This repo contains a website. This repo should have an issue template for Site Updates in here https://github.com/layer5io/service-mesh-performance/tree/master/.github/ISSUE_TEMPLATE.

**Desired Behavior**
Copy the [site_update.md](https://github.com/layer5io/meshery.io/tree/master/.github/ISSUE_TEMPLATE) GitHub issue template from the `layer5io/meshery.io` repo to make a new issue template in the `service-mesh-performance` repo.

### PR DESCRIPTION
**Pull request by shwosner**
**Description**

This PR fixes #163 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x ] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
Thank you, @shwosner. 👍 here is a set of commands that you can execute to ensure that each of your commits are signed off - https://github.com/layer5io/service-mesh-performance/pull/164/checks?check_run_id=1837395431

**Comment by cekbote** [comment]
@shwosner Hi, I think you probably missed it but you haven't signed off on one commit (DCO)?

**Comment by leecalcote** [comment]
Hi @shwosner, we're _this_ close to the finish line. Help us get your PR across it, if you would, by executing the `git` commands here - https://github.com/layer5io/service-mesh-performance/pull/164/checks?check_run_id=1837395431

**Comment by shwosner** [comment]
I followed the sign-off instructions, but DCO is still failing.
I'm closing this pull request and will try to make a new one.

**Pull request closed without merging**
