### PR TITLE
aligned footer items to center

### LINKED ISSUE #141: Fix the footer alignment for mobile view
**Current Behavior** :- 

Currently the footer section of the [SMP site](https://smp-spec.io/) is not optimized for mobile view. Most of the descriptive texts and icons are aligned to right. 

**Screenshot** :- 

recording

**Required Changes**

- Optimize this for mobile view.

### PR DESCRIPTION
**Pull request by manishkrjha**
Signed-off-by: Manish Jha <codernibba@gmail.com>

**Description**

This PR fixes #141 

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Neilblaze** [comment]
@manishkrjha aligning all footer elements to center alone won't be resolving issue #141 .
It was suggested to populate the change in mobile view only, not in the desktop view. Changing styling all the footer items on the global footer.scss file also reflect changes for desktop view too.

I'll suggest you to take the inspiration of [Meshery](http://meshery.io/)'s mobile view & make the similar changes for SMP site (only except the © text section).

**Review by Neilblaze — CHANGES_REQUESTED** [review]
↑↑

**Comment by manishkrjha** [comment]
@Neilblaze understood.

**Comment by Neilblaze** [comment]
@manishkrjha are you still on it?

**Comment by manishkrjha** [comment]
> @manishkrjha are you still on it?

Sorry I'm not able to work on it rn.

**Comment by Neilblaze** [comment]
It's ok. I'm catching it up! :heavy_check_mark:

**Pull request closed without merging**
