### PR TITLE
Added publish date & author name on blog posts

### LINKED ISSUE #112: [Site] List the author name and date on the blog posts
**Description**

In the [blog page](https://smp-spec.io/blog/) of [Service Mesh Performance](https://smp-spec.io/), currently we are missing out author name and date on the blog posts. 

**Expected Behavior**

The blog page should contain the respective author name and date on the blog posts. We can use the the style of [Layer5.io/blog](https://layer5.io/blog) for reference :)

scr1

scr2

NOTE : If anyone wants to fix the blog card padding issue in [blog](https://smp-spec.io/blog/) page, he/she might open a new issue regarding it & start fixing it!

### PR DESCRIPTION
**Pull request by Neilblaze**
**Description**
Added publish date & author name on blog posts. Also fixed the improper scaling issue of blog images!

This PR fixes #112

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by JubayerJoy — COMMENTED** [review]
LGTM 🚀

**Comment by JubayerJoy** [comment]
@leecalcote, I wonder why Netlify build was canceled 😕

**Comment by Neilblaze** [comment]
@Nikhil-Ladha resolve if you can 🙏

**Review by leecalcote — APPROVED** [review]
Not sure why Netlify thinks that there is no change.

**Pull request merged**
