### PR TITLE
Removed Google Logo from smp-spec.io

### LINKED ISSUE #129: [Docs] Remove Google Logo from smp-spec.io
**Current State:**
While individual Googler's have collaborated on SMP, Google as an entity has not publicly partnered / is not necessarily endorsing SMP currently.

**Desired State:**
Google's logo should not be present on the smp-spec.io site.

---
**Contributor Resources**
- [Service Mesh Performance documentation source](https://github.com/layer5io/service-mesh-performance/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/layer5io/service-mesh-performance/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

### PR DESCRIPTION
**Pull request by geraldmaboshe**
Signed-off-by: Gerald Maboshe <maboshegerald1@gmail.com>

**Description**
Google's logo has been removed from smp-spec.io site

This PR fixes #129 

**Notes for Reviewers**
N/A

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — APPROVED** [review]

**Comment by leecalcote** [comment]
Thank you, @geraldmaboshe

**Review by JubayerJoy — COMMENTED** [review]
Nice work @geraldmaboshe 🎈 
How about deleting the google logo from `assets/img/contributors/google-logo.svg` as we are not using that anymore?

**Comment by geraldmaboshe** [comment]
> Nice work @geraldmaboshe 🎈
> How about deleting the google logo from `assets/img/contributors/google-logo.svg` as we are not using that anymore?

Yeah @JubayerJoy , it makes sense. Are you going to create an issue for this so I can link it to a new PR since this is already merged?

**Comment by JubayerJoy** [comment]
Hi @geraldmaboshe,
I think this changes are best kept with in the scope of this particular issue.

You can commit this change in youe branch that is merged. We can then again marge this branch with master.

Cheers!

**Comment by geraldmaboshe** [comment]
> Hi @geraldmaboshe,
> I think this changes are best kept within the scope of this particular issue.
> 
> You can commit this change in your branch that is merged. We can then again marge this branch with `master`.
> 
> Cheers!

@JubayerJoy  [PR](https://github.com/layer5io/service-mesh-performance/pull/135) done

**Pull request merged**
