### PR TITLE
KubeCon video and slides added

### LINKED ISSUE #146: [Site] Add KubeCon EU Talk and Video
**Current Behavior**
The "Discreetly Studying the Effects of Individual Traffic Control Functions" talk from KubeCon EU 2020 explains SMP. 

**Desired Behavior**
This talk's video and slides should be on the [smp-spec.io](https://smp-spec.io) site. 

- video: https://layer5.io/projects/service-mesh-performance
- slides: https://calcotestudios.com/talks/decks/slides-kubecon-eu-2020-discreetly-studying-the-effects-of-individual-traffic-control-functions.html

### PR DESCRIPTION
**Pull request by dDab-panda**
Signed-off-by: Aayush <aayush.bcode@gmail.com>

**Description**

This PR fixes #146

**Notes for Reviewers**

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by Neilblaze** [comment]
@dDab-panda thanks for contributing to SMP. Before we merge the PR, the following changes are requested. Screenshots are shared for reference.

- For desktop view, add a little bit of **_whitespace_** just below `Discreetly Studying the Effects of Individual Traffic Control Functions` header.
smp1

- Fix the responsiveness of the slides for the mobile view. **(Priority High)**
smp2

- Migrate the inline styles to the respective CSS file! Also, I shall suggest defining a class to the break tags used to keep proper symmetry.

Correct if I miss any! @Nikhil-Ladha

**Review by Neilblaze — CHANGES_REQUESTED** [review]
^^

**Review by Neilblaze — APPROVED** [review]
LGTM :+1: 
Thank you @dDab-panda ! :smile:

**Review by JubayerJoy — APPROVED** [review]
Awesome!
LGTM :+1:

**Review by Neilblaze — APPROVED** [review]

**Review by Nikhil-Ladha — APPROVED** [review]
Looks good. Thank you @dDab-panda 🙂

**Pull request merged**
