### PR TITLE
Add section for CNCF in SMP homepage

### LINKED ISSUE #198: Add CNCF logo to smp-spec.io homepage
**Desired State of the service-mesh-performance site**
Service Mesh Performance is now a CNCF project.

There should be a section in the [smp-spec.io](https://smp-spec.io/) home page that shows this.

Resources-

[cncf-horizontal-color.svg](https://github.com/cncf/artwork/blob/master/other/cncf/horizontal/color/cncf-color.svg)

Title of the section: "Service Mesh Performance is a Cloud Native Computing Foundation project."

### PR DESCRIPTION
**Pull request by alphaX86**
Signed-off-by: Aadhitya A <aadhitya864@gmail.com>

**Description**
None

This PR fixes #198 

**Notes for Reviewers**
Make sure to check if the SVG size is okay...

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Review by leecalcote — CHANGES_REQUESTED** [review]
Screen Shot 2021-06-28 at 11 03 15 AM
Thank you. Will you close the gap between the text and the logo, while increasing the gap between the text and the blog section?

**Comment by alphaX86** [comment]
> Thank you. Will you close the gap between the text and the logo, while increasing the gap between the text and the blog section?

That's what I felt a bit off... will try!

**Comment by alphaX86** [comment]
image
I still couldn't figure out why a space is automatically added even after modifying CSS in line 😖

**Comment by leecalcote** [comment]
I haven't looked, but could be padding inside of the SVG itself.

**Review by leecalcote — APPROVED** [review]
Thank you, @alphaX86

**Comment by leecalcote** [comment]
Addresses items in CNCF onboarding checklist: https://github.com/cncf/toc/issues/676

**Pull request merged**
